### ISSUE TITLE
dart_frog not recognized!

### ISSUE THREAD

**Issue by immanewel** [Mobterest/dart_frog_tutorial#1]
I am using windows I have successful installed dart_frog_cli by the following command

``` dart pub global activate dart_frog_cli ```

when I list the globals I see dart_frog using the following command

``` dart pub global list```

but when creating a project using the following command 

``` dart_frog create hello_world```

I get the following mesage

'dart_frog' is not recognized as an internal or external command,
operable program or batch file.

![image](https://github.com/Mobterest/dart_frog_tutorial/assets/3966060/71948e8b-a2d7-456c-80f1-d4c3d9cebb0e)

**Comment by Mobterest** [comment]
Hey there. 

I have found this solution to help: Try close the command line/terminal and restart the IDE

**Comment by immanewel** [comment]
Thanks for the suggestion, I even restart the machine without success. I will pick your brain tomorrow for further elaboration.

**Comment by immanewel** [comment]
I have solved it, it had something to do with environment variables. After setting ```C:\Users\<user>\AppData\Local\Pub\Cache\bin``` it worked
